title: Coppermind
tagline: Your tagline here
author:
  name: Author

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - kramdown-parser-gfm
  
paginate: 2

tags_path: /tags/
categories_path: /categories/
